export const metaData = {
    title: "Aravind Vijayan | Full-Stack Developer & Web Engineer",
    description: "Full-stack developer skilled in React, Next.js, Node.js, PostgreSQL, and building modern web applications with high performance and security.",
    keywords: [
        "Aravind Vijayan",
        "Full-Stack Developer",
        "React Developer",
        "Next.js Developer",
        "Node.js Engineer",
        "JavaScript Developer",
        "Web Developer",
        "Software Engineer",
        "Frontend Developer",
        "Backend Developer",
        "PostgreSQL",
        "Express.js",
        "TypeScript",
        "Tailwind CSS",
        "Freelance Developer",
        "Web Application Developer",
        "SEO-friendly Websites",
    ],
    applicationName: "Aravind Vijayan Portfolio",
    generator: "Next.js",
    openGraph: {
        title: "Aravind Vijayan | Full-Stack Developer",
        description: "Passionate full-stack developer specializing in React, Next.js, Node.js, and PostgreSQL. Explore my projects and skills.",
        url: "https://aravindvijayan.vercel.app",
        siteName: "Aravind Vijayan Portfolio",
        images: [
            {
                url: "https://aravindvijayan.vercel.app/image.png",
                width: 1200,
                height: 630,
                alt: "Aravind Vijayan Portfolio",
            },
        ],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: "Aravind Vijayan | Full-Stack Developer",
        description: "Building modern, scalable web applications with Next.js, React, and Node.js.",
        images: ["https://aravindvijayan.vercel.app/image.png"],
    },
    icons: {
        icon: "/image.png",
        apple: "/image.png",
    },
    robots: "index, follow",
    viewport: "width=device-width, initial-scale=1.0",
};